---
- name: Install Above
  ansible.builtin.import_tasks:
    file: tools/above.yml
  tags:
    - all_tools
    - above

- name: Install AD-Miner
  ansible.builtin.import_tasks: 
    file: tools/ad-miner.yml
  tags:
    - all_tools
    - ad-miner

- name: Install ADExplorerSnapshot
  ansible.builtin.import_tasks: 
    file: tools/adexplorersnapshot.yml
  tags:
    - all_tools
    - adexplorersnapshot

- name: Install ADSearch
  ansible.builtin.import_tasks:
    file: tools/adsearch.yml
  tags:
    - all_tools
    - adsearch

- name: Install AzureHound
  ansible.builtin.import_tasks:
    file: tools/azurehound.yml
  tags:
    - all_tools
    - azurehound

- name: Install Bloodhound
  ansible.builtin.import_tasks: 
    file: tools/bloodhound.yml
  tags:
    - all_tools
    - bloodhound

- name: Install BOFHound
  ansible.builtin.import_tasks:
    file: tools/bofhound.yml
  tags:
    - all_tools
    - bofhound

- name: Install Certipy
  ansible.builtin.import_tasks:
    file: tools/certipy.yml
  tags:
    - all_tools
    - certipy

- name: Install Corsy
  ansible.builtin.import_tasks:
    file: tools/corsy.yml
  tags:
    - all_tools
    - corsy

- name: Install CrackMapExec
  ansible.builtin.import_tasks:
    file: tools/crackmapexec.yml
  tags:
    - all_tools
    - crackmapexec

- name: Install EDRSilencer
  ansible.builtin.import_tasks:
    file: tools/edrsilencer.yml
  tags:
    - all_tools
    - edrsilencer

- name: Install Ek47
  ansible.builtin.import_tasks:
    file: tools/ek47.yml
  tags:
    - all_tools
    - ek47

- name: Install enum4linux
  ansible.builtin.import_tasks:
    file: tools/enum4linux.yml
  tags:
    - all_tools
    - enum4linux

- name: Install enum4linux-ng
  ansible.builtin.import_tasks:
    file: tools/enum4linux-ng.yml
  tags:
    - all_tools
    - enum4linux-ng

- name: Install Exploit Database
  ansible.builtin.import_tasks:
    file: tools/exploitdb.yml
  tags:
    - all_tools
    - exploitdb

- name: Install Ferox Buster
  ansible.builtin.import_tasks:
    file: tools/feroxbuster.yml
  tags:
    - all_tools
    - feroxbuster

- name: Install Gitleaks
  ansible.builtin.import_tasks:
    file: tools/gitleaks.yml
  tags:
    - all_tools
    - gitleaks

- name: Install GoSigThief
  ansible.builtin.import_tasks:
    file: tools/gosigthief.yml
  tags:
    - all_tools
    - gosigthief

- name: Install HackTricks
  ansible.builtin.import_tasks:
    file: tools/hacktricks.yml
  tags:
    - all_tools
    - hacktricks

- name: Install Havoc
  ansible.builtin.import_tasks:
    file: tools/havoc.yml
  tags:
    - all_tools
    - havoc

- name: Install havoc_profile_generator
  ansible.builtin.import_tasks:
    file: tools/havoc_profile_generator.yml
  tags:
    - all_tools
    - havoc_profile_generator

- name: Install Havoc-ProfileGenerator
  ansible.builtin.import_tasks:
    file: tools/havoc-profilegenerator.yml
  tags:
    - all_tools
    - havoc-profilegenerator

- name: Install impacket
  ansible.builtin.import_tasks:
    file: tools/impacket.yml
  tags:
    - all_tools
    - impacket

- name: Install inceptor
  ansible.builtin.import_tasks:
    file: tools/inceptor.yml
  tags:
    - all_tools
    - inceptor

- name: Install Sliver
  ansible.builtin.import_tasks: 
    file: tools/sliver.yml
  tags:
    - all_tools
    - sliver

- name: Install Burp Suite Pro
  ansible.builtin.import_tasks: 
    file: tools/burpsuite.yml
  tags:
    - all_tools
    - burp

- name: Install Cloud Fox
  ansible.builtin.import_tasks: 
    file: tools/cloudfox.yml
  tags:
    - all_tools
    - cloudfox

- name: Install Confused
  ansible.builtin.import_tasks: 
    file: tools/confused.yml
  tags:
    - all_tools
    - confused

- name: Install cssg
  ansible.builtin.import_tasks: 
    file: tools/cssg.yml
  tags:
    - all_tools
    - cssg

- name: Install krbrelayx
  ansible.builtin.import_tasks: 
    file: tools/krbrelayx.yml
  tags:
    - all_tools
    - krbrelayx

- name: Install ldapnomnom
  ansible.builtin.import_tasks: 
    file: tools/ldapnomnom.yml
  tags:
    - all_tools
    - ldapnomnom

- name: Install nmap-thingor
  ansible.builtin.import_tasks: 
    file: tools/nmap-thingor.yml
  tags:
    - all_tools
    - nmap-thingor

- name: Install peeas-ng
  ansible.builtin.import_tasks: 
    file: tools/peass-ng.yml
  tags:
    - all_tools
    - peass-ng

- name: Install powersploit
  ansible.builtin.import_tasks: 
    file: tools/powersploit.yml
  tags:
    - all_tools
    - powersploit

- name: Install prowler
  ansible.builtin.import_tasks: 
    file: tools/prowler.yml
  tags:
    - all_tools
    - prowler

- name: Install redteaming stuffs
  ansible.builtin.import_tasks: 
    file: tools/redteaming.yml
  tags:
    - all_tools
    - redteaming

- name: Install responder
  ansible.builtin.import_tasks: 
    file: tools/responder.yml
  tags:
    - all_tools
    - responder

- name: Install rubeus
  ansible.builtin.import_tasks: 
    file: tools/rubeus.yml
  tags:
    - all_tools
    - rubeus

- name: Install safetykatz
  ansible.builtin.import_tasks: 
    file: tools/safetykatz.yml
  tags:
    - all_tools
    - safetykatz

- name: Install scoutsuite
  ansible.builtin.import_tasks: 
    file: tools/scoutsuite.yml
  tags:
    - all_tools
    - scoutsuite

- name: Install seatbelt
  ansible.builtin.import_tasks: 
    file: tools/seatbelt.yml
  tags:
    - all_tools
    - setbealt

- name: Install sharpdpapi
  ansible.builtin.import_tasks: 
    file: tools/sharpdpapi.yml
  tags:
    - all_tools
    - sharpdpapi

- name: Install sharphound
  ansible.builtin.import_tasks: 
    file: tools/sharphound.yml
  tags:
    - all_tools
    - sharphound

- name: Install sharpup
  ansible.builtin.import_tasks: 
    file: tools/sharpup.yml
  tags:
    - all_tools
    - sharpup

- name: Install sigthief
  ansible.builtin.import_tasks: 
    file: tools/sigthief.yml
  tags:
    - all_tools
    - sigthief

- name: Install soaphound
  ansible.builtin.import_tasks: 
    file: tools/soaphound.yml
  tags:
    - all_tools
    - soaphound

- name: Install trufflehog
  ansible.builtin.import_tasks: 
    file: tools/trufflehog.yml
  tags:
    - all_tools
    - trufflehog

- name: Install webshells
  ansible.builtin.import_tasks: 
    file: tools/webshells.yml
  tags:
    - all_tools
    - webshells

- name: Install wordlists
  ansible.builtin.import_tasks: 
    file: tools/wordlists.yml
  tags:
    - all_tools
    - wordlists

- name: Install wsuxploit
  ansible.builtin.import_tasks: 
    file: tools/wsuxploit.yml
  tags:
    - all_tools
    - wsuxploit